[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1.48.0", features = [ "full" ] }
tokio-util = { version = "0.7.16", features = ["codec"] }
tiled = "0.14.0"
macroquad = "0.4.14"
macroquad-tiled = "0.2.1"
